Task_1_1_1
miqqra/OOP pull request #1
Opened 2022-09-13 14:12 UTC by miqqra

2022-09-15 06:49 UTC, Leidenn2509 requested changes
- Нужен скрипт сборки

2022-09-15 06:49 UTC, Leidenn2509 commented on Task_1_1_1/src/main/java/ru/nsu/krasnikov/Heap.java
> +        int[] sortedArray = new int[arrayLength];
Heapsort не должен использовать дополнительную память. Эта сортировка способна отсортировать исходный массив

2022-09-15 06:49 UTC, Leidenn2509 commented on Task_1_1_1/src/main/java/ru/nsu/krasnikov/Heap.java
> +public class Heap {
Название Heap звучит как структура данных, всё же стоит добавить что-то намекающее на сортировку

2022-09-18 06:30 UTC, Leidenn2509 commented on Task_1_1_1/src/main/java/ru/nsu/krasnikov/Heap.java
> +public class Heap {
Измените имя класса.

2022-09-18 06:30 UTC, Leidenn2509 commented on Task_1_1_1/src/main/java/ru/nsu/krasnikov/Heap.java
> +        int[] sortedArray = new int[arrayLength];
Всё ещё не исправлено. В Heap:21 вы выделяете память.

2022-09-18 06:32 UTC, Leidenn2509 requested changes
Нужно исправить замечания

2022-09-18 13:12 UTC, miqqra commented on Task_1_1_1/src/main/java/ru/nsu/krasnikov/Heap.java
> +public class Heap {
ping, исправил

2022-09-19 07:51 UTC, Leidenn2509 approved these changes

2022-09-19 07:51 UTC, merged