Task_2_3_1
miqqra/OOP pull request #13
Opened 2023-06-18 14:53 UTC by miqqra

2023-06-20 09:15 UTC, alradish requested changes
Пришлите мне mp4 с демонстрацией игры (где видно выполнение всех требований)

2023-06-20 10:17 UTC, miqqra commented
Скинул на почту НГУ

2023-06-20 12:40 UTC, alradish requested changes
У вас всё отлично, кроме увелечения змейки. Когда ваша змейка ест (заходит тайлом головы на тайл еды), она не изменяется, и растёт только в следующем фрейме.
Должно быть: если змейка съела еду то она не уменьшается

2023-06-20 13:33 UTC, miqqra commented
Не уменьшается?

2023-06-20 13:38 UTC, miqqra commented
![step1](https://github.com/miqqra/OOP/assets/75527785/5941df12-6dde-49a7-ae90-07bb8afb5b6c)
![step2](https://github.com/miqqra/OOP/assets/75527785/15dac5b8-01eb-4a9e-a135-3ebbe947eed0)
![step3](https://github.com/miqqra/OOP/assets/75527785/ce557e64-73ba-431e-864f-44e884495fe2)

То есть момент поедания должен быть на один тик раньше?

2023-06-20 14:36 UTC, miqqra commented
Понял ошибку, выслал новую запись игры

2023-06-21 15:23 UTC, alradish approved these changes

2023-06-21 15:23 UTC, merged