Task_1_2_1
miqqra/OOP pull request #3
Opened 2022-09-19 09:01 UTC by miqqra

2022-09-21 10:28 UTC, Leidenn2509 requested changes

2022-09-21 10:28 UTC, Leidenn2509 commented on README.md
> +![Drs6DIaAYI4](https://user-images.githubusercontent.com/75527785/190951582-210d7586-5ab8-4f44-9777-5af447b745be.jpg)
Все эти файлы (вокрфлоу, игнор и ридми) уже находятся в мастере, а значит здесь их быть не должно.
Обновите мастер 
- из консоли: перейдите на master и сделайте `git pull`
- из айдии: откройте окно управления ветками (слева снизу), нажмите на `master` и выбирайте `update`  
- 
После этого сделайте rebase
- Из консоли: на ветке с лабой выполняйте `git rebase master`
- Из айддии: на ветке с лабой откройте окно управления ветками, нажмите на местер и выбирайте `rebase current onto selected` (или что-то такое там должно быть)
И пушите

2022-09-21 10:28 UTC, Leidenn2509 commented on Task_1_2_1/build.bat
> +jar cf .\build_project\jar\MyStack.jar .\src\main\java\ru\nsu\krasnikov\MyStack.java
Это больше не нужно

2022-09-21 10:28 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/krasnikov/MyStack.java
> +    }
Хорошо бы поддержать и уменьшение

2022-09-21 10:28 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/krasnikov/MyStack.java
> +    public void push(E element) {
А если `null`?

2022-09-21 10:28 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/krasnikov/MyStack.java
> +    public void pushStack(E[] stack) {
Пушить нужно стек, а не массив

2022-09-21 10:28 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/krasnikov/MyStack.java
> +    public E pop() {
А если элементов 0?

2022-09-24 11:08 UTC, miqqra commented on Task_1_2_1/src/main/java/ru/nsu/krasnikov/MyStack.java
> +    public void push(E element) {
новая вариация Push отработает корректно, добавил тесты для push с null и pushStack c пустым стеком

2022-09-24 11:09 UTC, miqqra commented on README.md
> +![Drs6DIaAYI4](https://user-images.githubusercontent.com/75527785/190951582-210d7586-5ab8-4f44-9777-5af447b745be.jpg)
rebase предложил убрать merge конфликты, но файлы оставил уже в обновленном виде. Их лучше удалить или оставить в "неконфликтном" виде?

2022-09-27 10:15 UTC, Leidenn2509 requested changes
- В результате данного ПР у вас из репозитория удалиться первая лаба. Нужно починить гит

2022-09-27 10:15 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/krasnikov/StackInterface.java
> +    E[] popStack(int amountOfElements);
Ну попать тоже же стек надо, это же попСтек

2022-09-27 10:15 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/krasnikov/MyStack.java
> +        this.stack = stack;
А если этот начальный стек больше 10 по размеру?

2022-10-06 09:05 UTC, Leidenn2509 approved these changes

2022-10-06 18:22 UTC, merged