Task_1_2_2
miqqra/OOP pull request #4
Opened 2022-10-01 05:50 UTC by miqqra

2022-10-12 12:46 UTC, Leidenn2509 requested changes
- У вас ПР хочет удалить первую лабу
- Отнаследуйтесь от `Iterable`

2022-10-12 12:46 UTC, alradish commented on Task_1_2_2/src/main/java/ru/nsu/krasnikov/Tree.java
> +     */
Перенесите эти джавадоки в интерфейс

2022-10-12 12:46 UTC, alradish commented on Task_1_2_2/src/main/java/ru/nsu/krasnikov/TreeInterface.java
> +    Tree<E> add(Tree<E> node, Tree<E> subNode)
У вас тут зависимость странная. ТриИнтерфейс зависит на Три, который реализует ТриИнтерфейс

2022-10-12 12:46 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/krasnikov/Tree.java
> +    public Tree<E> getParent(Tree<E> node) {
Хочется, чтобы можно было получить родителя текущей ноды. Даже если у нас на руках нет всего дерева

2022-10-12 12:46 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/krasnikov/Tree.java
> +        }
Я не советую так использовать эксепшены, так как они не бесплатные с точки зрения производительности. Обычно методы по типу `find` возвращают null (Или `Optional.empty`) если не нашли то, что искали. Или есть метод `contains` который возвращает true/false.
Перепишите без злоупотребления эксепшенами

2022-10-18 09:55 UTC, Leidenn2509 requested changes
- У вас тут затесалась вторая лаба. Попробуйте вмержить мастер в текущую ветку.

2022-10-18 09:55 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/krasnikov/Tree.java
> +    public static class TreeIterator<T extends Tree<?>> implements Iterator<T> {
Перенесите его вконец класса

2022-10-18 09:55 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/krasnikov/Tree.java
> +    public static class TreeIterator<T extends Tree<?>> implements Iterator<T> {
Или даже в отдельный файл

2022-10-18 09:55 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/krasnikov/Tree.java
> +    public Tree<E> getParent(Tree<E> node) {
Добавьте просто `getParent`, чтобы не писать `node.getParent(node)`

2022-10-18 09:55 UTC, Leidenn2509 commented on Task_1_2_2/src/test/java/ru/nsu/krasnikov/TreeTest.java
> +    public void test() {
Разбейте это на различные тестовые методы. Один тест проверяет что-то одно по смыслу

2022-10-18 11:15 UTC, miqqra commented on Task_1_2_2/src/test/java/ru/nsu/krasnikov/TreeTest.java
> +    public void test() {
вторая лаба здесь появилась после rebase с мастером. После внесения правок просто мержить мастер в эту ветку или удалить вторую лабу из этого бранча?

2022-10-24 02:59 UTC, Leidenn2509 approved these changes

2022-10-24 02:59 UTC, merged