Task_1_3_1
miqqra/OOP pull request #6
Opened 2022-11-06 18:59 UTC by miqqra

2022-11-11 07:56 UTC, alradish requested changes

2022-11-11 07:56 UTC, alradish commented on Task_1_3_1/src/main/java/ru.nsu.krasnikov/SubStringSearch.java
> +    public SubStringSearch(String fileName, String pattern) throws FileNotFoundException {
Добавьте способ найходить подстроки в любом InputStream

2022-11-11 07:56 UTC, alradish commented on Task_1_3_1/src/main/java/ru.nsu.krasnikov/SubStringSearch.java
> +    private FileInputStream file;
Испльзуйте более общий интерфейс `InputStream`, так как вам должно быть всё равно где искать подстроки: в файлах, строках, или через сеть

2022-11-11 07:56 UTC, alradish commented on Task_1_3_1/src/main/java/ru.nsu.krasnikov/SubStringSearch.java
> +        for (char ignored : chars) {
```Java
for(int i = 1; i < chars.length; i++)
```
https://www.geeksforgeeks.org/default-array-values-in-java/

2022-11-11 07:56 UTC, alradish commented on Task_1_3_1/src/main/java/ru.nsu.krasnikov/SubStringSearch.java
> +    private void calcPatternZfunction() {
Вынесите этот код в отдельную функцию которая принимает char[]. В таком случае у вас не будет дублирования кода

2022-11-21 10:48 UTC, alradish requested changes

2022-11-21 10:48 UTC, alradish commented on Task_1_3_1/src/main/java/ru.nsu.krasnikov/SubStringSearch.java
> +    public SubStringSearch(String string, String pattern) {
Добавьте конструктор который принимает InputStream

2022-11-21 10:48 UTC, alradish commented on Task_1_3_1/src/main/java/ru.nsu.krasnikov/SubStringSearch.java
> +        }
Этот код и код ниже делает одно и тоже, считает Z функцию. Надо обобщить и убрать дублирование

2022-11-21 10:57 UTC, alradish commented on Task_1_3_1/src/main/java/ru.nsu.krasnikov/SubStringSearch.java
> +    public SubStringSearch(String fileName, String pattern) throws FileNotFoundException {
наверное даже лучше будет Reader

2022-11-21 11:58 UTC, miqqra commented on Task_1_3_1/src/main/java/ru.nsu.krasnikov/SubStringSearch.java
> +        }
z функция считается отдельно для паттерна и для стрима, в противном случае в одной функции я буду сначала считать z функцию для шаблона, а потом для стрима, потому что в стриме может запрашиваться сразу весь шаблон

2022-11-28 04:29 UTC, alradish commented on Task_1_3_1/src/main/java/ru.nsu.krasnikov/SubStringSearch.java
> +        }
Если я правильно понял о чём вы(что "придется" считать z для паттерна множество раз) то это нормально. В данном случае это будет лучше чем дублирование кода. Хотя в общем случае ваш алгоритм можно так обобщить, чтобы не пересчитывать z функцию для паттерна.

2022-11-28 04:31 UTC, alradish requested changes
Требование на отсутсвие дублирования кода критично.

2022-11-29 17:02 UTC, alradish approved these changes

2022-11-29 17:02 UTC, merged